import Head from "next/head";
import { SecondaryButton, Wrapper } from "../../lib/common/components/atoms";
import CreateCourse from "../../lib/features/courses/presentation/CreateCourse";

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="flex flex-col justify-center items-center h-screen ">
        <div className="w-1/4">
          <div>
            <div className="flex justify-end">
              <SecondaryButton className="mb-5">عودة</SecondaryButton>
            </div>
            <Wrapper>
              <CreateCourse />
            </Wrapper>
          </div>
        </div>
      </div>
    </div>
  );
}
