import Head from "next/head";
import Link from "next/link";
import { SecondaryButton, Wrapper } from "../../lib/common/components/atoms";
import MainLayout from "../../lib/common/components/layouts/main_layout";
import { useAuth } from "../../lib/features/auth/domain/usecases/use_auth";
import CreateCourse from "../../lib/features/courses/presentation/CreateCourse";

export default function Home() {
  const {} = useAuth({
    middleware: "auth",
  });
  return (
    <MainLayout>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="flex flex-col justify-center items-center min-h-[85vh] ">
        <div className="w-1/4">
          <div>
            <div className="flex ">
              <Link href="/">
                <SecondaryButton className="mb-5">عودة</SecondaryButton>
              </Link>
            </div>
            <Wrapper>
              <CreateCourse />
            </Wrapper>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
